<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <title>Phalcon PHP Framework</title>
        <link rel="shortcut icon" type="image/x-icon" href="<?php echo $this->url->get('img/favicon.ico')?>"/>
        <link rel="stylesheet" href="<?php echo $this->url->get('css/app.css')?>">
    </head>
    <body>
        <div id="application" class="container">

            <?php echo $this->getContent(); ?>

        </div>
        <script src="<?php echo $this->url->get('js/app.js')?>"></script>
    </body>
</html>
